services:
  migrate:
    build:
      context: .
      secrets:
        - envprod
    container_name: calrix_migrate
    env_file:
      - .env.prod
    environment:
      DATABASE_URL: postgresql://postgres:1234@postgres:5432/calrix
    command: sh -c "pnpm db:migrate && pnpm db:reset"
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - setup

  app:
    build:
      context: .
      secrets:
        - envprod
    container_name: calrix_app
    ports:
      - "3001:3000"
    env_file:
      - .env.prod
    environment:
      DATABASE_URL: postgresql://postgres:1234@postgres:5432/calrix
      REDIS_URL: redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    container_name: calrix_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: calrix
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d calrix"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: valkey/valkey:8-alpine
    container_name: calrix_valkey
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:

secrets:
  envprod:
    file: .env.prod
