export enum ErrorCode {
  // Auth
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",

  // Request
  BAD_REQUEST = "BAD_REQUEST",
  VALIDATION_ERROR = "VALIDATION_ERROR",

  // Resource
  NOT_FOUND = "NOT_FOUND",
  CONFLICT = "CONFLICT",

  // Rate Limit
  TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS",

  // AI
  AI_PROVIDER_ERROR = "AI_PROVIDER_ERROR",
  AI_GENERATION_FAILED = "AI_GENERATION_FAILED",
  AI_TOOL_EXECUTION_FAILED = "AI_TOOL_EXECUTION_FAILED",

  // Command Bar
  COMMAND_NOT_UNDERSTOOD = "COMMAND_NOT_UNDERSTOOD",
  ACTION_REQUIRES_CONFIRMATION = "ACTION_REQUIRES_CONFIRMATION",

  // Calendar
  CALENDAR_CONFLICT = "CALENDAR_CONFLICT",

  // Providers
  PROVIDER_TOKEN_MISSING = "PROVIDER_TOKEN_MISSING",
  PROVIDER_TOKEN_EXPIRED = "PROVIDER_TOKEN_EXPIRED",
  PROVIDER_RATE_LIMIT = "PROVIDER_RATE_LIMIT",
  PROVIDER_API_ERROR = "PROVIDER_API_ERROR",

  // System
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}
